server:
  port: 8084


spring:
  application:
    name: weather-collection-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yellow948/spring-cloud-config.git
          search-paths: config



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



